ARCHS = arm64

include $(THEOS)/makefiles/common.mk

TOOL_NAME = setuphelper
setuphelper_INSTALL_PATH = /Library/Application Support/GateToFreedom
setuphelper_FILES = main.c
setuphelper_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tool.mk
